// Auto-generated by sanitizeGeneratedFiles
export async function onRequest(context) {
  const { request } = context;
  const userId = new URL(request.url).searchParams.get('userId');
  const userData = {
    userId,
    savedResumes: [
      { id: 1, title: "Software Engineer Resume" },
      { id: 2, title: "Product Manager Resume" },
    ],
    preferences: {
      theme: "dark",
      language: "en",
    },
  };
  return new Response(JSON.stringify(userData), {
    headers: { 'Content-Type': 'application/json' },
  });
}